### ISSUE TITLE
User Experience Improvements

### ISSUE THREAD

**Issue by SatinWukerORIG** [RedEnder666/RickRoll_IDE#1]
Thank you for making this app! I believe that every rickroll developer appreciates your hard work!
However, as i use this software, i realized that some crucial enhancements should be made.
1) Support full screen
2) Introduction page right after opening the app.
just like what vscode has:
![vs1](https://user-images.githubusercontent.com/74630829/161369816-5e8f98b5-dd43-4d30-8faa-2b94a70d6406.PNG)
3) An icon on the editor's banner:
you can use the logo of Rickroll lang
![newlogo](https://user-images.githubusercontent.com/74630829/161369867-62c608ba-ac4b-43be-8c3f-90be15cd445a.jpg)
or the old logo: ![](https://github.com/Rick-Lang/rickroll-lang/blob/main/img/ico1.jpg?raw=true)

Thank you! and I will also contribute to this project

**Comment by RedEnder666** [comment]
Thank you for your response! 
I added resizing and fullscreen support today and yeah, i gonna add logo and main page later. =)
